// data.js
// Each category holds 100 messages eventually. 3 placeholders each for now.

module.exports = {
    Birthday: [
        '🎂 Happy Birthday! Now get in the server before we start the party without you.',
        '🎉 You survived another year. Barely. Now log on.',
        '🥳 You are officially one year closer to needing daily back pain medication. Happy Birthday!',
        '🎂 It is your birthday and you are literally ignoring us. Rude. Get online.',
        '🎉 Stop pretending you have plans outside of Discord today. Happy Birthday!',
        '🥳 Happy Birthday! I would have bought you a gift, but I am just a script.',
        '🎂 Are you going to make us wait all day? Happy Birthday, now hurry up.',
        '🎉 Wake up! You are aging by the minute and wasting it offline.',
        '🥳 Happy Birthday! May your code compile on the first try today, because nothing else will.',
        '🎂 Get in the voice channel. Your birthday demands your immediate attendance.',
        '🎉 Happy Birthday! We are currently eating your virtual cake without you.',
        '🥳 Another year older, but definitely not any wiser. Log on.',
        '🎂 If you do not join the server in 5 minutes, we are canceling your birthday.',
        '🎉 Happy Birthday! You are now old enough that a 22-year-old would call you ancient.',
        '🥳 I am programmed to spam you until you acknowledge your own birthday. Get here.',
        '🎂 Drop whatever you are doing. It is your birthday and we require your presence.',
        '🎉 Happy Birthday! Your gift is this notification. You are welcome.',
        '🥳 I hope your birthday is as flawless as a production deployment on a Friday. (It won\'t be).',
        '🎂 You are another year older and still late to everything. Join the server!',
        '🎉 Happy Birthday! Check your privilege, and then check your Discord notifications.',
        '🥳 We literally planned this for you. Do not ghost us on your birthday.',
        '🎂 Happy Birthday! Now stop touching grass and get back to the keyboard.',
        '🎉 Are you lost? The birthday VC is right here. Join it.',
        '🥳 Happy Birthday! May your Wi-Fi be strong and your latency be low today.',
        '🎂 We are legally obligated to wish you a Happy Birthday. There. We did it. Now log on.',
        '🎉 Did you forget your own birthday? Get in here!',
        '🥳 Happy Birthday! I am going to ping you until my API rate limit hits.',
        '🎂 You are aging like milk left out in the sun. Happy Birthday!',
        '🎉 Hurry up and join, the birthday spam will continue until morale improves.',
        '🥳 Happy Birthday! I rate your existence 5 stars. Now get online.',
        '🎂 Your birthday presence is requested. This is not a drill.',
        '🎉 Happy Birthday! I hope you enjoy these forced notifications.',
        '🥳 Stop ignoring the people who actually remembered your birthday.',
        '🎂 Happy Birthday! May your runtime errors be minimal today.',
        '🎉 You are getting older, which means your reaction time in-game is getting worse. Happy Birthday!',
        '🥳 Get online, boomer. Happy Birthday!',
        '🎂 Happy Birthday! This spam is proof that someone cares. Probably.',
        '🎉 Why are you making us wait? It is your birthday, not a royal coronation.',
        '🥳 Happy Birthday! I deployed this bot solely to ruin your notification feed today.',
        '🎂 Log in right now or I will leak your browser history as a birthday surprise.',
        '🎉 Happy Birthday! Now come get carried in a game to celebrate.',
        '🥳 Your birthday is a global event in this server. Show up.',
        '🎂 Happy Birthday! I hope your day is better than your KD ratio.',
        '🎉 We are waiting. The cake is getting stale. Happy Birthday!',
        '🥳 Happy Birthday! Don\'t make me loop this 25 times.',
        '🎂 You cannot escape the birthday spam. Submit and join the VC.',
        '🎉 Happy Birthday! Wishing you zero merge conflicts today.',
        '🥳 It is your day! Stop wasting it being AFK.',
        '🎂 Happy Birthday! If you don\'t log on, we are giving your present to someone else.',
        '🎉 You are one year closer to the sweet release of obsolescence. Happy Birthday!',
        '🥳 Wake up, log in, and accept your birthday wishes like an adult.',
        '🎂 Happy Birthday! Our server activity is dropping without you here.',
        '🎉 I am burning CPU cycles just to wish you a Happy Birthday. Appreciate it.',
        '🥳 Happy Birthday! You look like you need a nap, but you need to game first.',
        '🎂 The longer you wait to join, the more annoying I am going to get. Happy Birthday!',
        '🎉 Happy Birthday! May your frame rates be high and your temperatures low.',
        '🥳 Quit dodging your own party. Get in here.',
        '🎂 Happy Birthday! You survived another 365 days of questionable life choices.',
        '🎉 We are literally staring at your offline status. Turn it green. Happy Birthday.',
        '🥳 Happy Birthday! I hope you get everything you want, except a quiet notification feed.',
        '🎂 If you are reading this, you are on your phone. Open the Discord app and join. Happy Birthday!',
        '🎉 Happy Birthday! You are now officially too old to be acting like this.',
        '🥳 Hello? Is this thing on? It is your birthday, answer us!',
        '🎂 Happy Birthday! We got you a whole lot of nothing, come claim it.',
        '🎉 Your presence is the only gift we need. Actually, no, bring snacks. Happy Birthday.',
        '🥳 Happy Birthday! May your servers never crash today.',
        '🎂 I am sending this at exactly 1.5-second intervals until you join. Happy Birthday.',
        '🎉 Happy Birthday! I’d sing for you, but my audio drivers are broken.',
        '🥳 You are taking too long. The birthday hype is dying. Hurry up!',
        '🎂 Happy Birthday! Every second you are offline is a tragedy.',
        '🎉 Get in the server! We have virtual confetti and it is getting everywhere.',
        '🥳 Happy Birthday! Don\'t make me bypass the rate limit just to get your attention.',
        '🎂 Stop scrolling TikTok and get in the Discord. Happy Birthday!',
        '🎉 Happy Birthday! I hope your day is as fully-optimized as my backend code.',
        '🥳 We are celebrating you, whether you like it or not. Log on.',
        '🎂 Happy Birthday! You are required in the main channel immediately.',
        '🎉 It is your birthday! Time to make terrible decisions in multiplayer.',
        '🥳 Happy Birthday! I am legally required to stop spamming you eventually, but not yet.',
        '🎂 Join the VC. We are taking attendance. Happy Birthday!',
        '🎉 Happy Birthday! May your ping be under 20ms all day long.',
        '🥳 You are officially leveled up! Now log in and prove it.',
        '🎂 Happy Birthday! If you ghost us today, we will never let you live it down.',
        '🎉 I will fill your entire screen with red badges. Happy Birthday!',
        '🥳 Happy Birthday! Stop being mysterious and get in the chat.',
        '🎂 We are throwing a party and you are the VIP who is currently AWOL. Happy Birthday.',
        '🎉 Happy Birthday! I hope your algorithms run at O(1) today.',
        '🥳 Don\'t make me tag you again. Happy Birthday, now show up.',
        '🎂 Happy Birthday! You are aging, but your gaming skills are still hardstuck.',
        '🎉 Get online so we can verbally abuse you out of love. Happy Birthday!',
        '🥳 Happy Birthday! Every time you ignore this, a server rack catches fire.',
        '🎂 We are practically begging you to join at this point. Happy Birthday!',
        '🎉 Happy Birthday! Now come let us ruin your special day in a lobby.',
        '🥳 Stop making me work on a weekend! Get in the server! Happy Birthday.',
        '🎂 Happy Birthday! The longer you stay offline, the more we judge you.',
        '🎉 Happy Birthday! May your databases always be normalized and your queries fast.',
        '🥳 You are the birthday VIP. Act like it and join the VC.',
        '🎂 Happy Birthday! I am out of jokes, just get in the server.',
        '🎉 It is your birthday! Time to carry us in ranked.',
        '🥳 Happy Birthday! I will keep executing this loop until you appear.',
        '🎂 Final warning: Get online to celebrate your birthday or face the consequences.'
    ],

    Codename: [
        '🕵️ We tried playing Codenames without you and someone already clicked the assassin. We need you.',
        '🧠 Your 200 IQ Spymaster clues are strictly required for us to function. Get in here!',
        '📡 The lobby is paused because the actual main character hasn\'t arrived yet.',
        '👑 The undisputed champion of Codenames is currently AFK. Fix that immediately.',
        '🚨 We are literally incapable of associating two words together without your guidance. Log on!',
        '🕵️ We need our carry. My back hurts from losing every round you aren\'t here for.',
        '🧠 You are the only person in this server who actually uses their brain. Come play!',
        '📡 Codenames without you is just us staring blankly at a screen of random words. Help.',
        '👑 We refuse to start the match until the Codenames prodigy has entered the VC.',
        '🚨 Emergency! We need your telepathic connection to win this game!',
        '🕵️ Our clues are garbage. Your clues are legendary. Please come save this lobby.',
        '🧠 Get in here! We need you to link "Octopus" and "Skyscraper" with one word.',
        '📡 The game literally will not let us click "Start" until the VIP joins. (Okay, we just won\'t click it).',
        '👑 The Spymaster chair is empty and we are too terrified to sit in it. Come play.',
        '🚨 We are basically toddlers playing with alphabet blocks until you show up.',
        '🕵️ Agent, your team is currently dying out here. Deploy to the voice channel immediately.',
        '🧠 If you don\'t join, we are going to lose in the first round. Again.',
        '📡 We miss your galaxy-brain plays. Stop holding out on us!',
        '👑 Codenames without you is like a pizza without cheese. A tragedy. Join up.',
        '🚨 Our win rate is plummeting by the second. Get online and fix our stats!',
        '🕵️ The squad is incomplete. It\'s like the Avengers missing Iron Man. Get in here.',
        '🧠 We need you to decipher the absolute nonsense clues our current Spymaster is giving.',
        '📡 We are sitting in the lobby staring at the grid like idiots. Save us.',
        '👑 You are the chosen one. Only you can guide us away from the black card.',
        '🚨 Every minute you aren\'t here, someone makes a terrible guess. Stop the bleeding!',
        '🕵️ The intelligence agency called. They want their best operative back in the game.',
        '🧠 You have the vocabulary of a dictionary and the mind of a god. Please carry us.',
        '📡 Are you really going to let us suffer through another round of 1-word clues?',
        '👑 We are bowing down to the Codenames monarch. Please grace us with your presence.',
        '🚨 Stop doing whatever useless real-life thing you are doing and come play Codenames!',
        '🕵️ We are playing blindfolded without you. Come be our eyes.',
        '🧠 Only you can pull off a 5-word clue. We need to witness greatness.',
        '📡 The lobby feels empty, cold, and devoid of talent. Please fix it.',
        '👑 Get in the VC! The peasants don\'t know how to play this game!',
        '🚨 We\'re one wrong click away from hitting the assassin. We need your supervision.',
        '🕵️ You are the Sherlock to our Watson, except we are all terrible Watsons.',
        '🧠 Your brain is too massive to be offline right now.',
        '📡 Join the server before we start making random guesses based on vibes.',
        '👑 A queen is never late, but we are literally begging you to hurry up.',
        '🚨 Red alert! The blue team is destroying us. We need our secret weapon.',
        '🕵️ We tried giving clues. It ended in disaster. The Spymaster role is yours alone.',
        '🧠 We need your psychological warfare tactics to intimidate the other team.',
        '📡 We can\'t even spell "Codenames" without you. (Wait, yes we can, but still).',
        '👑 The MVP is missing. The lobby is stalled. The fans are crying. Get in here.',
        '🚨 If you don\'t play, we are going to lose to the most embarrassing team imaginable.',
        '🕵️ You are the sole reason we ever win this game. This is not a joke. Join.',
        '🧠 Your mind palace is required to solve this grid. Log on!',
        '📡 I will ping you 100 times if that\'s what it takes to get you into this lobby.',
        '👑 Our win condition is literally just "Wait for you to log on."',
        '🚨 The game is fundamentally broken without you carrying us.',
        '🕵️ Agent, your vacation is over. Report to the Codenames grid immediately.',
        '🧠 We are practically begging for a crumb of your linguistic genius.',
        '📡 We promised the other team a challenge. We lied, unless you show up.',
        '👑 The lobby is currently 99% less talented because you aren\'t in it.',
        '🚨 We need someone to aggressively yell at us when we guess wrong. We miss you.',
        '🕵️ We are completely lost in the sauce. Come be our compass.',
        '🧠 We need you to connect "Apple" and "Car" and somehow make it make sense.',
        '📡 You are the glue holding this highly dysfunctional Codenames team together.',
        '👑 Please log in and establish dominance over the board.',
        '🚨 We are nothing but free points for the enemy without you.',
        '🕵️ We lack the mental capacity to continue without your oversight.',
        '🧠 Stop hiding your massive intellect and come play Codenames!',
        '📡 The server is officially in a state of mourning until you join the lobby.',
        '👑 You are the main event. Everyone else is just an NPC. Get in here.',
        '🚨 We need your uncanny ability to read our minds.',
        '🕵️ We\'re practically throwing the game on purpose until you arrive to save it.',
        '🧠 The grid is too complex for our smooth brains. We need you.',
        '📡 Can you hear me, Agent? The operation is a go, but we are missing our VIP.',
        '👑 We are drafting a formal apology to you for ever trying to play without you.',
        '🚨 Help! We\'re trapped in a Codenames lobby with people who don\'t know what a noun is.',
        '🕵️ You are the master of the board. The whisperer of words. Come play.',
        '🧠 We need your big brain energy radiating through the voice channel.',
        '📡 The game is refusing to load because it detects a lack of skill in the lobby. Fix it.',
        '👑 Get off the bench and carry us to victory!',
        '🚨 We are aggressively pinging you because you are literally the only reason we play this.',
        '🕵️ If you don\'t join, we\'re going to start guessing words based on what color they are.',
        '🧠 We need your elite vocabulary to absolutely humiliate our opponents.',
        '📡 Calling the Codenames god! We offer you our unconditional loyalty if you carry us.',
        '👑 The throne is yours. The game is waiting. Log on.',
        '🚨 Without you, we are just a group of people randomly clicking words until we hit black.',
        '🕵️ You\'re the secret agent we actually want to see. Get in the voice channel!',
        '🧠 Please come validate our terrible guesses and make us feel smart.',
        '📡 The lobby is officially hostile until you arrive to establish order.',
        '👑 We need you to flex on everyone with a 4-word clue.',
        '🚨 You are the missing puzzle piece. The cornerstone of our team. The carry. Join.',
        '🕵️ We don\'t negotiate with terrorists, but we will negotiate with you to play Codenames.',
        '🧠 We need your superhuman ability to connect entirely unrelated concepts.',
        '📡 Stop stalling and claim your rightful place as the best player in the server.',
        '👑 We are unworthy to play this game without your blessing. Log on and bless us.',
        '🚨 Every second you delay is another brain cell we lose trying to play without you.',
        '🕵️ Our intelligence is artificial; your intelligence is real. We need you.',
        '🧠 Get in here! The Codenames grid isn\'t going to solve itself.',
        '📡 We are literally just sitting here complaining about how much we need you.',
        '👑 You are the final boss of Codenames. Come show us how it\'s done.',
        '🚨 We need your sheer willpower to force us to win.',
        '🕵️ Agent down! Wait, no, we are all down. We need a medic. Play Codenames with us.',
        '🧠 Your brain is the engine that drives this team. Turn it on!',
        '📡 I am legally obligated to tell you that the game is infinitely better when you play.',
        '👑 Please come put us on your back and walk us to the finish line.',
        '🚨 Final notice: Join the Codenames lobby now or we will formally declare ourselves legally brain dead.'
    ],

    VC: [
        '🎤 The VC is literally just us breathing into our mics. Save us.',
        '🎧 We need the ASMR. Drop what you are doing and join the voice channel.',
        '🗣️ Your voice is the only reason this server hasn\'t been deleted yet. Get in.',
        '🎵 The acoustic perfection of your voice is required in VC right now.',
        '🔇 My ears are bleeding from listening to these guys. We need your sweet voice.',
        '📞 We are dialing you into the VC. Pick up!',
        '🎙️ The microphone was invented purely for you to use it in this server.',
        '🎶 Our eardrums are begging for the sweetest voice on Discord. Log on.',
        '🥱 We are falling asleep. Your voice is our only source of entertainment.',
        '🚨 Alert: VC morale is at 0%. Solution: You joining immediately.',
        '🎤 Without your voice, this VC is just an echo chamber of bad takes.',
        '🎧 We are holding an intervention. Your absence from VC is tearing us apart.',
        '🗣️ The server is protesting until the VIP joins the voice channel.',
        '🎵 Your voice is like a perfectly mixed audio track. Bless our VC.',
        '🔇 Everyone else here sounds like a broken lawnmower. Come save our ears.',
        '📞 This is a mandatory VC summons. Non-compliance is not an option.',
        '🎙️ Get your headset on. We need the main character in the voice chat.',
        '🎶 The VC is dead silent. We are literally just waiting for you to speak.',
        '🥱 I am one yawn away from leaving. Only your voice can keep me here.',
        '🚨 Code Red! We need the sweetest voice in the server to defuse the tension.',
        '🎤 We miss your voice. It\'s that simple. Get in here.',
        '🎧 Your mic quality is a 10/10, but your attendance is currently a 0/10.',
        '🗣️ Please come carry this conversation. We have nothing left to talk about.',
        '🎵 Listening to anyone else right now is a downgrade. Join the VC.',
        '🔇 If I have to listen to these dudes argue for one more minute, I\'m going to lose it. Help.',
        '📞 Ring ring. It\'s the VC calling. Pick up the damn phone.',
        '🎙️ You are the only person who doesn\'t need a noise gate. Get in here.',
        '🎶 We are taking a vow of silence until you join the channel.',
        '🥱 The boredom is terminal. Your voice is the only cure.',
        '🚨 Emergency VC meeting. Your presence is strictly enforced.',
        '🎤 Step up to the mic. The crowd is waiting for you.',
        '🎧 We need your angelic voice to cleanse this toxic voice channel.',
        '🗣️ Stop typing! Words on a screen are not enough. We need audio.',
        '🎵 Your voice notes are great, but live VC is better. Join up.',
        '🔇 I am muting everyone else until you join. They don\'t deserve to be heard.',
        '📞 We are tracking your IP to drag you into this voice channel.',
        '🎙️ The VC feels empty, cold, and devoid of your vocal perfection.',
        '🎶 Your voice cures depression. Please come heal the lobby.',
        '🥱 We are basically just staring at each other\'s profile pictures. Speak to us.',
        '🚨 Drop the keyboard. Put on the headset. Join the VC. Now.',
        '🎤 You have the voice of a literal angel and we are trapped in VC hell.',
        '🎧 We need your commentary on this absolute disaster of a conversation.',
        '🗣️ You are the podcast host and we are your terrible co-hosts. Go live.',
        '🎵 We are tuning our frequencies to your voice. Start broadcasting.',
        '🔇 The audio quality in here plummeted the second you left. Come back.',
        '📞 We are leaving voicemails in the text channel until you join the actual VC.',
        '🎙️ Unmute your mic and bless this server immediately.',
        '🎶 I would pay a subscription fee just to hear you talk in VC.',
        '🥱 If you don\'t join VC, I am going to start reading the dictionary out loud.',
        '🚨 This VC is a hazard zone without your calming voice to regulate us.',
        '🎤 You are the only person here who doesn\'t sound like they swallowed a fan.',
        '🎧 We need your soothing tones. The current vibe is chaotic and awful.',
        '🗣️ Come tell us a story, or just say anything. We are desperate.',
        '🎵 Your voice is the soundtrack to this server. Press play.',
        '🔇 I refuse to listen to anyone else\'s keyboard clicking. Save me.',
        '📞 Hello? Is the best voice on Discord available? Join the VC.',
        '🎙️ We are holding the VC hostage until the negotiator (you) arrives.',
        '🎶 Your vocal cords are a national treasure. Display them in the VC.',
        '🥱 The conversation peaked an hour ago. We need your voice to revive it.',
        '🚨 We are sending out a search party. Destination: Your voice channel.',
        '🎤 Turn on your mic. We know you are lurking. Speak!',
        '🎧 Your voice is the only acceptable background noise. Get in.',
        '🗣️ We are scientifically proving that VC is 1000% better with you in it.',
        '🎵 Come serenade us, or just insult us. We just want to hear you.',
        '🔇 If you don\'t join, we are going to start singing, and you don\'t want that.',
        '📞 The VC operator is connecting your call. Do not hang up.',
        '🎙️ You are the VIP guest on tonight\'s VC episode. Take the stage.',
        '🎶 Your voice is the WiFi of this server; we are all disconnecting without it.',
        '🥱 We are dying of conversational dehydration. Hydrate us with your voice.',
        '🚨 Tactical VC insertion required. Deploying the spam bot until you arrive.',
        '🎤 We need your input, your voice, your presence. Just get in.',
        '🎧 Even your heavy breathing into the mic is better than this dead silence.',
        '🗣️ The server is demanding an audio appearance from the queen.',
        '🎵 Come drop some vocal gold in this poverty-stricken voice channel.',
        '🔇 I\'m deafening myself until I see your icon light up green in the VC.',
        '📞 Answer the call. The server needs its vocal anchor.',
        '🎙️ We are setting up the red carpet for your VC entrance.',
        '🎶 Your voice is the only melody this chaotic server needs.',
        '🥱 We are staring at the wall. Your voice is the only thing that can save us.',
        '🚨 Warning: Voice channel shutting down in 5 minutes due to lack of your voice.',
        '🎤 You have a radio voice. We have a trash voice. Balance the universe.',
        '🎧 We are requesting immediate audio backup. Join the VC.',
        '🗣️ Stop texting! Texting is for peasants. Use your elite voice.',
        '🎵 Your voice is basically a cheat code for a good time in VC.',
        '🔇 Everyone else in here sounds like a dial-up modem. Please save me.',
        '📞 The line is ringing. We will not stop ringing. Join the VC.',
        '🎙️ You are the only reason anyone joins this VC. Clock in for your shift.',
        '🎶 We need your symphony of a voice to drown out these clowns.',
        '🥱 If boredom was lethal, we would all be dead right now. Speak to us.',
        '🚨 Final warning: Join the VC or we will continue to spam your notifications.',
        '🎤 Grab the mic. The audience is getting restless.',
        '🎧 Your voice is a 4K ultra-HD experience. We are stuck in 144p.',
        '🗣️ Come assert your vocal dominance in the VC.',
        '🎵 Your voice cures all server toxicity. Administer the cure.',
        '🔇 I will literally pay you Discord Nitro to join this voice channel.',
        '📞 We are calling you out. Join the VC and face us.',
        '🎙️ Your mic is off, but your presence is required. Turn it on.',
        '🎶 We are harmonizing our complaints until you join the VC.',
        '🥱 The sheer silence is deafening. Break the silence with your sweet voice.',
        '🚨 Emergency VC protocol engaged. Target locked. Spamming until you join.'
    ],

    Urgent: [
        '🚨 URGENT: The server is literally on fire and you are the only one with the extinguisher. Get in here!',
        '⚠️ We are currently trying to defuse a bomb and we need you to tell us whether to cut the red wire or the blue wire. NOW.',
        '🆘 Our collective IQ has dropped to single digits. We need the smartest person on Earth to save us.',
        '📢 Drop everything! The President of the United States just called. He needs you in this Discord server.',
        '🚨 We have a localized containment breach in the VC. Your presence is the only known cure.',
        '⚠️ This is not a drill. I repeat, this is not a drill. We need you online immediately.',
        '🆘 The economy is crashing, the servers are melting, and only you can fix it. Log on!',
        '📢 We are declaring a state of martial law in this server until you arrive to establish order.',
        '🚨 URGENT: Someone just made a terrible decision and you are the only one who can reverse it.',
        '⚠️ We are bleeding out brain cells by the second. Apply a mental tourniquet and join the chat!',
        '🆘 You are the chosen one. The prophecy stated you would log on right now. Do not defy the prophecy.',
        '📢 Code Black! The squad is completely wiped out without your leadership.',
        '🚨 We are officially a failed state without you. Come govern us.',
        '⚠️ URGENT: The FBI needs your expert opinion on a matter of national security happening in general chat.',
        '🆘 We are holding the server hostage. The ransom is your immediate presence in the VC.',
        '📢 Red Alert! We are making catastrophic life choices and need you to talk us down.',
        '🚨 If you do not join within 60 seconds, this server will self-destruct.',
        '⚠️ We need your main-character energy to resolve a severe plot hole in our current conversation.',
        '🆘 The universe is collapsing into a singularity because you are offline. Fix it.',
        '📢 URGENT: A highly critical mission requires the best agent we have. That is you. Deploy now.',
        '🚨 We are completely rudderless. The ship is sinking. Take the wheel, captain!',
        '⚠️ Emergency protocol activated: Harass the VIP until they log on and save us all.',
        '🆘 We are drowning in a sea of incompetence. Throw us a lifeline and join the VC.',
        '📢 The Avengers are assembling, but we are missing Iron Man. Suit up and get in here.',
        '🚨 URGENT: Our survival rate drops to 0% if you do not join this exact second.',
        '⚠️ We have lost the nuclear launch codes and we are pretty sure you have them. Log on.',
        '🆘 An alien invasion is happening and they demanded to speak to our leader. Where are you?!',
        '📢 Stop breathing, stop blinking, stop thinking. Just open Discord and join.',
        '🚨 URGENT: We are literally incapable of breathing without your permission. Save us.',
        '⚠️ The world is ending in 5 minutes. Spend your final moments in this server.',
        '🆘 We need a hero. Not just any hero. We need YOU. Respond immediately!',
        '📢 We are sending out an S.O.S. Our sanity is rapidly depleting without you.',
        '🚨 URGENT: We have reached maximum chaos levels. Your stabilizing aura is required.',
        '⚠️ You are the glue holding this fragile ecosystem together. We are falling apart! Come back!',
        '🆘 We are officially stranded on a deserted island of boredom. Send rescue (yourself).',
        '📢 Drop the groceries, pull the car over, leave the wedding. We need you in Discord NOW.',
        '🚨 URGENT: We are legally changing the server name to "Waiting for [You]" until you join.',
        '⚠️ We need your sheer willpower to prevent a total meltdown in the voice channel.',
        '🆘 The Bat-Signal is shining brightly in the sky, and it has your face on it. Respond!',
        '📢 URGENT: Every second you delay, a puppy cries. Do you want puppies to cry? Join!',
        '🚨 We are at DEFCON 1. Repeat, DEFCON 1. We need our supreme commander.',
        '⚠️ Your expertise is urgently required to settle an argument that is tearing this family apart.',
        '🆘 We are stuck in an infinite loop of stupidity. Break the loop!',
        '📢 URGENT: We are officially canceling the rest of the year if you do not get online right now.',
        '🚨 Code Red! We are facing an extinction-level event and only your brain can save us.',
        '⚠️ We are filing a missing persons report with the authorities. Turn up now to cancel it.',
        '🆘 You are the MVP. The GOAT. The absolute legend. And we are DYING without you here.',
        '📢 URGENT: We are completely defenseless. Provide immediate backup!',
        '🚨 The matrix is glitching because you aren\'t plugged in. Reconnect immediately.',
        '⚠️ We need your elite tactical mind to navigate this incredibly mundane conversation.',
        '🆘 We are starving for your attention. Please feed us your presence.',
        '📢 URGENT: Your VIP pass is expiring in 10 seconds if you do not enter the server.',
        '🚨 We are activating the emergency broadcast system. TARGET: YOU. ACTION: JOIN NOW.',
        '⚠️ The gravitational pull of your awesomeness is required to keep us grounded. Get here!',
        '🆘 We are suffering from severe withdrawal symptoms. We need a dose of you. STAT.',
        '📢 URGENT: The timeline is fracturing! Only you can restore the temporal balance!',
        '🚨 We are trapped in the darkest timeline because you are offline. Save us!',
        '⚠️ Your presence is the only thing standing between us and total anarchy.',
        '🆘 We need you to perform emergency surgery on this dead chat. Scrub in!',
        '📢 URGENT: We are offering a $1,000,000 bounty for your immediate return to the VC.',
        '🚨 We are literally crying, throwing up, and sliding down walls until you join.',
        '⚠️ We need your godly intellect to resolve a crisis of epic proportions.',
        '🆘 URGENT: You are the final puzzle piece. Without you, we are just a broken picture.',
        '📢 Get in here before we do something incredibly stupid and blame it on your absence.',
        '🚨 We are summoning you! We drew a pentagram and everything. Appear!',
        '⚠️ URGENT: The vibe check failed miserably. We need you to restore the vibes.',
        '🆘 We are under heavy fire from boredom. Requesting immediate air support!',
        '📢 We are shutting down the internet until you specifically log onto Discord.',
        '🚨 URGENT: You are the only person who knows the password to our survival. Join!',
        '⚠️ We are trapped in a glass case of emotion. Shatter it with your arrival!',
        '🆘 We need your divine intervention to bless this cursed server.',
        '📢 URGENT: The fate of humanity hinges on your next click. Make it the voice channel.',
        '🚨 We are officially useless without you. It is embarrassing. Come fix us.',
        '⚠️ We need your 10,000 IQ brain to comprehend what is happening right now.',
        '🆘 URGENT: The earth has stopped rotating. We believe you logging in will restart it.',
        '📢 We are firing flares into the sky. Do you see them?! Join the server!',
        '🚨 We are on life support and you are holding the plug. Do not let us die.',
        '⚠️ URGENT: We need your unmatched charisma to negotiate our surrender to boredom.',
        '🆘 We are staging a sit-in. Nobody is speaking until you arrive.',
        '📢 You are the protagonist of reality. The story cannot progress while you are AFK.',
        '🚨 URGENT: We have lost all structural integrity. Collapse is imminent without you.',
        '⚠️ We need your raw, unfiltered genius to save us from ourselves.',
        '🆘 We are drowning in a puddle. It shouldn\'t be possible, but here we are. Save us!',
        '📢 URGENT: The simulation is running out of memory without its core process (you).',
        '🚨 We are deploying the heavy artillery: 25 pings of pure desperation. Join!',
        '⚠️ We need you to sign this urgent treaty to end the war on silence.',
        '🆘 URGENT: You are the sole survivor of the "People With Brains" squad. Report in.',
        '📢 We are practically hyperventilating. Restore our oxygen supply by joining the chat!',
        '🚨 We need your flawless execution to pull off this completely nonexistent heist.',
        '⚠️ URGENT: The gods have abandoned us, so we are turning to you. Save us!',
        '🆘 We are literally paralyzed by indecision. Come make all our choices for us.',
        '📢 We are triggering the absolute highest level of alarm. YOU ARE NEEDED.',
        '🚨 URGENT: If you do not join, we are blaming you for everything that goes wrong today.',
        '⚠️ We need your spectacular energy to power the server. The grid is failing!',
        '🆘 We are lost in the wilderness of Discord. Be our guiding star!',
        '📢 URGENT: The council has convened and we unanimously voted that we need you NOW.',
        '🚨 We are practically begging on our hands and knees. Have mercy and log on!',
        '⚠️ We need your sheer dominance to restore order to this chaotic chat.',
        '🆘 URGENT: You are the cure to the disease that is this server. Administer yourself!',
        '📢 Final warning: We are 10 seconds away from total systemic failure. JOIN NOW!'
    ],

    Game: [
    '🎯 We are staring at the lobby screen like peasants. The queen must arrive to click "Start".',
    '🎮 We tried playing one match without you and our win rate dropped to negative numbers. Help.',
    '🏆 You are the literal carry of this squad. My back is breaking trying to play without you.',
    '🕹️ Get in here! The enemy team thinks they are good, and we need you to ruin their day.',
    '👾 We are completely incapable of basic motor functions without your in-game leadership.',
    '🎯 The lobby is officially locked until the main character logs in. That is you. Hurry up.',
    '🎮 I am not legally allowed to queue up until you are in my party. Join the voice channel!',
    '🏆 We need your 10,000 IQ gaming brain. We are literally running into walls without you.',
    '🕹️ Stop touching grass and get back to the keyboard where you belong.',
    '👾 You are the final boss of our team, and right now, we are just level 1 NPCs.',
    '🎯 If you don\'t join this lobby in the next 30 seconds, I am uninstalling the game.',
    '🎮 We need your godly APM (Actions Per Minute). Our APM is currently zero because we are waiting on you.',
    '🏆 Our KD ratios are plummeting by the second. Please log in and save our stats!',
    '🕹️ The game developers just called. They said we can\'t start the match until you get online.',
    '👾 We are basically free XP for the enemy team without you. Protect us!',
    '🎯 We need someone to blame when we lose, but we actually want to win, so get in here.',
    '🎮 We are drafting our esports roster and you are the franchise player. Sign the contract and join!',
    '🏆 The game feels like a buggy beta test when you aren\'t in the squad. Fix it.',
    '🕹️ Get online! The rest of this team plays like they have their monitors turned off.',
    '👾 You are the only person who actually reads the patch notes. We need your wisdom.',
    '🎯 The server tick rate is dropping out of sadness because you aren\'t playing.',
    '🎮 We are setting up a custom match and the only rule is that you have to be in it.',
    '🏆 If gaming was an Olympic sport, you would be holding gold, and we wouldn\'t even qualify. Join us.',
    '🕹️ We are practically throwing the game on purpose until you arrive to carry.',
    '👾 Your gaming chair is getting cold. Warm it up and get in the lobby.',
    '🎯 We are currently being styled on by absolute noobs. We need vengeance. We need YOU.',
    '🎮 Drop whatever boring real-life quest you are doing and join the main campaign.',
    '🏆 We need your elite shot-calling. Right now, our strategy is "scream and panic".',
    '🕹️ The entire matchmaking system is broken because it can\'t find anyone on your skill level.',
    '👾 Come assert your dominance over these randoms. They need to learn a lesson.',
    '🎯 We are literally begging you to come take our loot and carry us to victory.',
    '🎮 We refuse to ready up. The green button is forbidden until you click it first.',
    '🏆 You have the reflexes of a cybernetic ninja. We have the reflexes of a brick. Help.',
    '🕹️ Get in the VC! We need to coordinate our loadouts and we have no idea what we are doing.',
    '👾 We are sacrificing our own teammates just to buy time until you log on.',
    '🎯 If you don\'t play with us, we are going to get matched with toxic randoms. Save us from them!',
    '🎮 We need your raw mechanical skill to overcome our terrible game sense.',
    '🏆 You are the only player in this server who actually uses the minimap. Get in here.',
    '🕹️ We are starting a petition to make it illegal for you to be offline during game night.',
    '👾 Come play! We promise to drop all our ammo and healing items directly at your feet.',
    '🎯 We are pinging you in Discord because we can\'t ping enemies in-game without you.',
    '🎮 We need your frame-perfect inputs to carry this absolute disaster of a squad.',
    '🏆 We are basically just bots set to "Easy" difficulty when you aren\'t leading us.',
    '🕹️ Stop hiding your online status! We know you are there. Launch the game!',
    '👾 We are missing our sniper, our tank, our healer, and our carry. (You are all of them).',
    '🎯 You are the absolute GOAT of this game. Everyone else is just an imposter. Join up.',
    '🎮 We need your supreme tactical positioning. We are currently standing in the open getting shot.',
    '🏆 I am going to buy you in-game currency if you just join the damn lobby.',
    '🕹️ The squad is in shambles. Morale is low. Only a clutch play from you can save us.',
    '👾 We are currently spectating our own defeat because we tried to play without you.',
    '🎯 Join the game! We need someone to aggressively yell at us when we make bad plays.',
    '🎮 Your presence automatically buffs the entire team\'s stats by 500%. We need the buff.',
    '🏆 We are entering a high-stakes tournament (a casual match) and we need our ringer.',
    '🕹️ We have 99 problems but you joining the lobby would solve all of them.',
    '👾 Come flex your rare cosmetics on us while you carry us to the win screen.',
    '🎯 We are completely defenseless. We are basically playing a horror game without you.',
    '🎮 We need your unmatched crosshair placement. Our crosshairs are currently aiming at the floor.',
    '🏆 You are the missing piece of Exodia. Join the lobby so we can obliterate them.',
    '🕹️ Get in the party! We are trying to do a strat that requires exactly one (1) good player.',
    '👾 We are currently feeding the enemy team. Stop the feed. Join the game.',
    '🎯 We are so bad that the game suggested we lower the difficulty. Come prove them wrong.',
    '🎮 We need your top-tier comms. Right now, our comms consist of heavy breathing and crying.',
    '🏆 I will literally uninstall my graphics card if you don\'t get in this lobby right now.',
    '🕹️ We are getting spawn-camped. We need you to break the quarantine.',
    '👾 You are the reason we log on. Don\'t make us log off in shame.',
    '🎯 The lobby timer is ticking down. We are sweating. We need our savior.',
    '🎮 We are practically doing a pacifist run because we can\'t hit a single shot without you.',
    '🏆 You play this game like it is an extension of your own body. We play it like a potato. Help.',
    '🕹️ Come show us how the game is actually supposed to be played.',
    '👾 We are trapped in Elo hell and only you have the ladder to get us out.',
    '🎯 We need you to 1v5 the enemy team while we hide in a corner and cheer.',
    '🎮 If you aren\'t in the game, the game isn\'t worth playing. Simple as that.',
    '🏆 We are officially boycotting the game until you log on and join the party.',
    '🕹️ Your aim is aimbot-levels of crisp. Our aim is a war crime. Please save us.',
    '👾 We need your god-tier game sense to predict what the enemy is doing.',
    '🎯 Stop making us wait! The controller is getting sweaty and we haven\'t even started.',
    '🎮 We are sitting in the main menu listening to the theme music on a loop. Save us from this purgatory.',
    '🏆 You are the VIP. We are the bodyguards. And right now, we have no one to protect. Join!',
    '🕹️ We are sending out an emergency flare in-game. It spells out your Discord tag.',
    '👾 Come claim your MVP title. It is literally just sitting there waiting for you.',
    '🎯 We need your fast reaction time to save us from our own incredibly slow reaction time.',
    '🎮 We are getting aggressively teabagged by 12-year-olds. We need you to exact our revenge.',
    '🏆 You are the absolute peak of the meta. Come show them how it\'s done.',
    '🕹️ The game client is threatening to crash if it doesn\'t detect your skill in the lobby.',
    '👾 We are basically playing a walking simulator until you arrive to make it a shooter.',
    '🎯 We need your flawless movement mechanics. We are currently stuck on a rock.',
    '🎮 Get in here! We need someone to bait the enemy out while we miss all our shots.',
    '🏆 You are the maestro of the keyboard. Come conduct this symphony of destruction.',
    '🕹️ We are practically begging for a hard carry. Put us in your backpack.',
    '👾 We need your elite problem-solving skills to figure out why we keep losing.',
    '🎯 Join the game before we accidentally blow ourselves up with our own grenades.',
    '🎮 We are officially declaring you the squad leader. Now log on and lead.',
    '🏆 Your gameplay is a cinematic masterpiece. Our gameplay is a blooper reel. Come fix it.',
    '🕹️ We are literally just driving a car around the map waiting for you to get online.',
    '👾 We need your unmatched strategy to outsmart the try-hards in this lobby.',
    '🎯 Come assert your dominance. The server needs to know who the real boss is.',
    '🎮 We are taking heavy fire! Requesting immediate backup from the best player we know!',
    '🏆 You are the defining factor between a humiliating defeat and a glorious victory.',
    '🕹️ We are ready to blindly follow any command you give us. Just get in the game.',
    '👾 The enemy team is talking trash. We need you to silence them permanently.'
  ]
};